name: RPGAdditions
version: 0.1
main: me.drkmatr1984.RPGAdditions.RPGAdditions
api-version: 1.13
description: Adds new weapons, armor, and items to Spigot Servers
depend: [AdditionsAPI]
softdepend: [LightAPI, ShinyItems, Werewolf]